test_split:
    - - - 0.7
        - ":"
model_type: "MaskedSequenceTransformer"
model_path: trained_models/skc_r150_o0.5_pr0.1_seq10_mint3_ng5_moleft_15-08_14-00-06/model_epoch_0.pth
data_path: data/tfco_datasets/total_1_5382_monocon_05
dataset_name:
    - skc_r150_o0_pr0.1_poi100_100_nr55000
max_vehicles: 80
radius: 100
centerpoint: null
sequence_len: 10
min_timesteps_seen: 3
batch_size: 64
seed: 13
filter: true
vehicle_filter_mode: "below"
vehicle_selection_mode: "nearest"
num_vehicles: 80
project_name: "test_run"
distance_weight: 400.0
class_weight: 1.0
wandb_mode: "online"
network_configs:
    MaskedTransformer: 
        full_attention: false
        vehicle_only_attention: false
        embed_dim: 64
        num_heads: 4
        num_layers: 2
        dropout: 0.1
        use_pos_embed: true
        use_type_embed: false

normalization: "radius" #or "radius"