dataset_path: data/tfco_datasets/total_1_5382_monocon_05
dataset_name:
    - skc_r150_o0_pr0.1_poi100_100_nr55000
train_split:
    - - - ':'
        - 0.7
      - - 0.8
        - ':'
    
val_split:
    - - - 0.7
        - 0.8

max_vehicles: 25
radius: 100
centerpoint: null
sequence_len: 10
min_timesteps_seen: 3
num_epochs: 100
batch_size: 32
seed: 13
project_name: "tfco_gridsize"
track_emissions: true 
filter: true
vehicle_filter_mode: "below"
vehicle_selection_mode: "nearest"
num_vehicles: 25
wandb_mode: "disabled"
scheduler:
    type: default
    init_lr: 0.0001
    step_size: 5000
    gamma: 0.9
distance_weight: 400.0
class_weight: 1.0
load_complete_model: null
validation_frequency: 1
save_frequency: 25

default_scheduler_config:
    type: default
    init_lr: 0.0001
    step_size: 5000
    gamma: 0.9

cosine_scheduler_config:
    type: cosine
    startup_steps: 5000
    min_lr: 1e-6

network_configs:
    MaskedTransformer: 
        full_attention: false
        vehicle_only_attention: false
        embed_dim: 64
        num_heads: 4
        num_layers: 2
        dropout: 0.1
        use_pos_embed: true
        use_type_embed: false


