
detection_method: '2d-raytracing' # '2d-raytracing', '3d-raytracing', 'emulation'
start_times: 
    - 3600
    - 75600
explicit_start_times: 
    - 21600
    - 36000
    - 57600
num_steps: 1000
num_loops: 100 # run simulation several times to get more data (traffic will be different each time)
fco_penetration_rate: 0.05
filename: '5382_monocon_05'
model_path: 'ViTEncoderDecoder_monocon_new' # only used for the nn detection method
center_point: 
    - 5382
    - 5288
radius: 250
polygons: 'sumo_sim/ingolstadt.poly.xml' # 
rou_file: 'motorized_routes_2020-09-16_24h_dist.rou.xml'
sumo_file: '24h_sim.sumocfg'
variate_traffic: true
inflow_time: 600 # time to allow traffic to flow into the simulation
